// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Table.Project.Data;

#nullable disable

namespace Table.Project.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Table.Project.Models.FifaSoccerer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FifaSoccerers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 31,
                            Name = "Marc-André ter Stegen",
                            Position = "Goalkeeper",
                            Score = 88,
                            Skill = "Goalkeeping"
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            Name = "Jules Koundé",
                            Position = "Defender",
                            Score = 85,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 3,
                            Age = 24,
                            Name = "Ronald Araújo",
                            Position = "Defender",
                            Score = 86,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 4,
                            Age = 21,
                            Name = "Pedri",
                            Position = "Midfielder",
                            Score = 88,
                            Skill = "Passing"
                        },
                        new
                        {
                            Id = 5,
                            Age = 19,
                            Name = "Gavi",
                            Position = "Midfielder",
                            Score = 84,
                            Skill = "Dribbling"
                        },
                        new
                        {
                            Id = 6,
                            Age = 35,
                            Name = "Robert Lewandowski",
                            Position = "Forward",
                            Score = 91,
                            Skill = "Finishing"
                        },
                        new
                        {
                            Id = 7,
                            Age = 26,
                            Name = "Frenkie de Jong",
                            Position = "Midfielder",
                            Score = 87,
                            Skill = "Passing"
                        },
                        new
                        {
                            Id = 8,
                            Age = 23,
                            Name = "Ferran Torres",
                            Position = "Forward",
                            Score = 82,
                            Skill = "Dribbling"
                        },
                        new
                        {
                            Id = 9,
                            Age = 21,
                            Name = "Ansu Fati",
                            Position = "Forward",
                            Score = 81,
                            Skill = "Finishing"
                        },
                        new
                        {
                            Id = 10,
                            Age = 31,
                            Name = "Sergi Roberto",
                            Position = "Midfielder",
                            Score = 79,
                            Skill = "Versatile"
                        },
                        new
                        {
                            Id = 11,
                            Age = 31,
                            Name = "Thibaut Courtois",
                            Position = "Goalkeeper",
                            Score = 90,
                            Skill = "Goalkeeping"
                        },
                        new
                        {
                            Id = 12,
                            Age = 26,
                            Name = "Éder Militão",
                            Position = "Defender",
                            Score = 85,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 13,
                            Age = 31,
                            Name = "David Alaba",
                            Position = "Defender",
                            Score = 85,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 14,
                            Age = 34,
                            Name = "Toni Kroos",
                            Position = "Midfielder",
                            Score = 88,
                            Skill = "Passing"
                        },
                        new
                        {
                            Id = 15,
                            Age = 38,
                            Name = "Luka Modrić",
                            Position = "Midfielder",
                            Score = 88,
                            Skill = "Vision"
                        },
                        new
                        {
                            Id = 16,
                            Age = 25,
                            Name = "Federico Valverde",
                            Position = "Midfielder",
                            Score = 87,
                            Skill = "Versatile"
                        },
                        new
                        {
                            Id = 17,
                            Age = 23,
                            Name = "Vinícius Júnior",
                            Position = "Forward",
                            Score = 90,
                            Skill = "Dribbling"
                        },
                        new
                        {
                            Id = 18,
                            Age = 23,
                            Name = "Rodrygo",
                            Position = "Forward",
                            Score = 85,
                            Skill = "Dribbling"
                        },
                        new
                        {
                            Id = 19,
                            Age = 30,
                            Name = "Antonio Rüdiger",
                            Position = "Defender",
                            Score = 84,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 20,
                            Age = 23,
                            Name = "Aurélien Tchouaméni",
                            Position = "Midfielder",
                            Score = 84,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 21,
                            Age = 27,
                            Name = "Andreas Christensen",
                            Position = "Defender",
                            Score = 83,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 22,
                            Age = 23,
                            Name = "Sergiño Dest",
                            Position = "Defender",
                            Score = 78,
                            Skill = "Dribbling"
                        },
                        new
                        {
                            Id = 23,
                            Age = 33,
                            Name = "Marcos Alonso",
                            Position = "Defender",
                            Score = 79,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 24,
                            Age = 24,
                            Name = "Ferran Jutglà",
                            Position = "Forward",
                            Score = 77,
                            Skill = "Finishing"
                        },
                        new
                        {
                            Id = 25,
                            Age = 25,
                            Name = "Iñaki Peña",
                            Position = "Goalkeeper",
                            Score = 75,
                            Skill = "Goalkeeping"
                        },
                        new
                        {
                            Id = 26,
                            Age = 24,
                            Name = "Fran García",
                            Position = "Defender",
                            Score = 80,
                            Skill = "Defense"
                        },
                        new
                        {
                            Id = 27,
                            Age = 34,
                            Name = "Joselu",
                            Position = "Forward",
                            Score = 82,
                            Skill = "Finishing"
                        },
                        new
                        {
                            Id = 28,
                            Age = 21,
                            Name = "Eduardo Camavinga",
                            Position = "Midfielder",
                            Score = 85,
                            Skill = "Versatile"
                        },
                        new
                        {
                            Id = 29,
                            Age = 29,
                            Name = "Ferland Mendy",
                            Position = "Defender",
                            Score = 81,
                            Skill = "Defense"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
